### ISSUE TITLE
Compat with Steve's Carts 2

### ISSUE THREAD

**Issue by Leonyx1175** [alfuken/terracart#1]
Oops... Edit:

Currently, Terracart conflicts with SC2 Reborn - When someone tries to place a cart, the right-click on the rail causes it to conflict. Any way to change this to either a keybind or only when right-clicking with an empty hand?

**Comment by alfuken** [comment]
You got it. :) Updated the mod and uploaded versions for 1.10.2 and 1.7.10
You can download the jar here (choose corresponding branch), or from Curse (when it gets approved by moderator system)

As of now, it's hardcoded to be empty hand, but when I get to know this stuff better, I'll probably add config for that.
