### ISSUE TITLE
[feature request] change right click on rails

### ISSUE THREAD

**Issue by Zygus42** [alfuken/terracart#2]
We've had a few people having problems in abandoned mines with your mod on, because they right click on the rails while fighting or doing other stuff and get whisked off.   Any chance to change to a shift-right click, or to need an empty hand when right clicking ?  Or perhaps config settings to let you choose which you prefer ?

**Comment by alfuken** [comment]
You got it. :) Updated the mod and uploaded versions for 1.10.2 and 1.7.10
You can download the jar here (choose corresponding branch), or from Curse (when it gets approved by moderator system)
